### ISSUE TITLE
autohelm can get in a weird state when it fails to download a private chart

### ISSUE THREAD

**Issue by geojaz** [reactiveops/autohelm#42]
```bash
...
The datadog agent is listening on port 8126.

2018-08-22 09:45:44 es-MacBook-Pro.local root[2798] DEBUG Installing fluentd
2018-08-22 09:45:44 es-MacBook-Pro.local root[2798] DEBUG Repository for fluentd is OrderedDict([('git', 'git@github.com:reactiveops/ro-charts.git')])
2018-08-22 09:45:44 es-MacBook-Pro.local root[2798] WARNING Ignoring path argument ""! Remove path when chart exists at the repository root
2018-08-22 09:45:44 es-MacBook-Pro.local git.cmd[2798] DEBUG Popen(['git', 'fetch', '--tags', '-v', 'origin'], cwd=/Users/e/workspace/projects/democracyworks/democracyworks-infrastructure/helm/cache/archive/git@github_com:reactiveops_ro-charts_git, universal_newlines=True, shell=None)
Enter passphrase for key '/Users/e/workspace/projects/democracyworks/democracyworks-infrastructure/inventory/default/config/pr': 
2018-08-22 09:45:48 es-MacBook-Pro.local git.cmd[2798] DEBUG AutoInterrupt wait stderr: 'fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.'
2018-08-22 09:45:48 es-MacBook-Pro.local root[2798] ERROR Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --tags -v origin
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
2018-08-22 09:45:48 es-MacBook-Pro.local root[2798] DEBUG Removing sparse checkout config
2018-08-22 09:45:48 es-MacBook-Pro.local git.cmd[2798] DEBUG Popen(['git', 'config', 'core.sparseCheckout', 'false'], cwd=/Users/e/workspace/projects/democracyworks/democracyworks-infrastructure/helm/cache/archive/git@github_com:reactiveops_ro-charts_git, universal_newlines=False, shell=None)
Traceback (most recent call last):
  File "/Users/e/.pentagon/venv/bin/autohelm", line 67, in <module>
    cli()
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/e/.pentagon/venv/bin/autohelm", line 46, in plot
    h.install()
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/autohelm/autohelm.py", line 216, in install
    if not self.install_chart(chart, self._charts[chart]):
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/autohelm/autohelm.py", line 337, in install_chart
    repository_name = self.ensure_repository(release_name, chart_name, chart.get('repository'), chart.get('version', "master"))        
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/autohelm/autohelm.py", line 329, in ensure_repository
    if self._fetch_git_chart(chart_name, repository_git, version,  repository_path) is False:
  File "/Users/e/.pentagon/venv/lib/python2.7/site-packages/autohelm/autohelm.py", line 185, in _fetch_git_chart
    raise e
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --tags -v origin
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```

**Comment by ejether** [comment]
Please provide all necessary information to reproduce the error.
